dist: trusty
language: go
go:
  - 1.9
services:
  - postgresql
addons:
  postgresql: "9.6"

go_import_path: github.com/vulcanize/vulcanizedb

before_install:
  # ginkgo golint dep migrate
  - make installtools
  - bash ./scripts/install-postgres-10.sh
  - npm install -g ganache-cli

before_script:
  - go get -u github.com/pressly/sup/cmd/sup
  - sudo -u postgres createdb vulcanize_private
  - make migrate NAME=vulcanize_private
  - bash ./pkg/transformers/start_test_chain.sh

script:
  - make test

notifications:
  email: false

after_script:
  - bash ./pkg/transformers/stop_test_chain.sh
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - sup --debug staging deploy
