dist: trusty
language: go
go:
- 1.12
services:
- postgresql
addons:
  postgresql: '11.2'
go_import_path: github.com/makerdao/vdb-mcd-transformers
before_install:
- make installtools
- bash ./scripts/install-postgres-11.sh
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update && sudo apt-get install yarn
script:
- env GO111MODULE=on make test
- env GO111MODULE=on make integrationtest
notifications:
  email: false
env:
  matrix:
    secure: KPD5A3lwN5pGtBgvLn+cyqLlZdfgB9jhXUtAp1bYUrtRx5H+5mBVEH87hbXqyoAAPAK1vAml/ZqLMOAoTBky0QveWdqVBCKY/ia46oEmERMFmXMtLPJSVm0nFarQl8AiQVDUaJhAnxQu2SJlyKyQ8Jy1kx8+ZLmYgFZE/u/LRksNP5y2apU+SNHEKNgurWVLescNPVYlJy1j99vt7m8R67c1ADPVXkzqSe5fdOpUftlyl+QJac3AvPr2b2/LdqYA/e3cJ3LYDl/WYLV/KWGlJF8PbOiVoXzteGcR0AHpXdbcu6jLG2hM0ZYmx4OShhJspAGA/8AAhuTbTgtpEyUkGN9MfIvuuXu6RYwMbmUSdwo7FBbPehhfR/KUM+UAqUtDDBgdQBMF8PzHBlsUaxQwgUJo8R5DVdXpo0us375rcILNsGq3xQniFrJe8CJCpjaYqYDlZgEOoFnaR1sPIACsrci4CDeyWQ+iMfkZTcA5Izwbk0Y03MPyX7C2gJ3UrT1cwYLze7iozvR4qNIjTZ3vJCAU+agBT+vtISz5AcmCUgI4+4qzM+y6vdPx4P71yhp7BL/CD8GuLJLRsD1wxVqSwqAuuvYcpB/rcljZQNAkW7p99QXLza1U2r/1gcFfz4HcxyMoRhfms5dSlsAQBHOvAm9/5nV9mX13IF2lRmpptSM=
