[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    user     = "vulcanize"
    password = "vulcanize"
    port     = 5432

[client]
    ipcPath  = "http://kovan0.vulcanize.io:8545"

[datadog]
    name     = "maker_vdb_staging"

[exporter]
    home     = "github.com/vulcanize/vulcanizedb"
    name     = "storageTransformerExporter"
    save     = false
    transformerNames = [
        "pit",
        "vat",
        "vow",
        "cat",
        "drip"
    ]
    [exporter.pit]
        path = "transformers/storage/pit/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.vat]
        path = "transformers/storage/vat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.vow]
        path = "transformers/storage/vow/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.cat]
        path = "transformers/storage/cat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.drip]
        path = "transformers/storage/drip/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"

[filesystem]
    storageDiffsPath = "INSERT-PATH-TO-STORAGE-DIFFS"

[contract]
    [contract.address]
            cat      = "0x2f34f22a00ee4b7a8f8bbc4eaee1658774c624e0"
            jug      = "0x25a008Bf942CE6D5b362f91ed7aE3e4104286a12"
            pit      = "0xe7cf3198787c9a4daac73371a38f29aaeeced87e"
            vat      = "0x67fd6c3575fc2dbe2cb596bd3bebc9edb5571fa1"
            old_vat  = "0xcd726790550afcd77e9a7a47e86a3f9010af126b"
            vow      = "0x17560834075da3db54f737db74377e799c865821"