[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    user     = "vulcanize"
    password = "vulcanize"
    port     = 5432

[client]
    ipcPath  = ""

[datadog]
    name     = "maker_vdb_staging"

[exporter]
    home     = "github.com/vulcanize/vulcanizedb"
    name     = "storageTransformerExporter"
    save     = false
    transformerNames = [
        "cat",
        "jug",
        "vat",
        "vow"
    ]
    [exporter.cat]
        path = "transformers/storage/cat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.jug]
        path = "transformers/storage/jug/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.vat]
        path = "transformers/storage/vat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"
    [exporter.vow]
        path = "transformers/storage/vow/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
        rank = "0"

[filesystem]
    storageDiffsPath = "INSERT-PATH-TO-STORAGE-DIFFS"

[contract]
    [contract.address]
            MCD_CAT  = "0x35f3d8997ef261c7961bd7c07ddc390f5cf76bd3"
            MCD_JUG  = "0x25a008Bf942CE6D5b362f91ed7aE3e4104286a12"
            MCD_VAT  = "0x67fd6c3575fc2dbe2cb596bd3bebc9edb5571fa1"
            MCD_VOW  = "0x17560834075da3db54f737db74377e799c865821"
