[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    user     = "vulcanize"
    password = "vulcanize"
    port     = 5432

[client]
    ipcPath  = "http://kovan0.vulcanize.io:8545"

[datadog]
    name     = "maker_vdb_staging"

[exporter]
    home     = "github.com/vulcanize/vulcanizedb"
    name     = "storageTransformerExporter"
    save     = false
    transformerNames = [
        "pit",
        "vat",
        "vow",
        "cat",
        "drip"
    ]
    [exporter.pit]
        path = "transformers/storage/pit/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
    [exporter.vat]
        path = "transformers/storage/vat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
    [exporter.vow]
        path = "transformers/storage/vow/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
    [exporter.cat]
        path = "transformers/storage/cat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
    [exporter.drip]
        path = "transformers/storage/drip/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"

[filesystem]
    storageDiffsPath = "INSERT-PATH-TO-STORAGE-DIFFS"

[contract]
    [contract.address]
            pit      = "0xe7cf3198787c9a4daac73371a38f29aaeeced87e"
            vat      = "0xcd726790550afcd77e9a7a47e86a3f9010af126b"
            vow      = "0x3728e9777B2a0a611ee0F89e00E01044ce4736d1"
            cat      = "0x2f34f22a00ee4b7a8f8bbc4eaee1658774c624e0"
            drip     = "0x891c04639a5edcae088e546fa125b5d7fb6a2b9d"
