
# This composition runs header sync and execute with automatic restarts.
# Environment variables for each can be set in their respective `.env` file,
# or overridden with a shell variable.

version: "3.7"
services:
  header-sync:
    image: makerdao/vdb-headersync:v0.0.11-lite
    env_file: mainnet-1.0.1.env
    environment:
      - CLIENT_IPCPATH="https://geth0.mainnet.makerfoundation.com:8545"
      - DATABASE_NAME=vdb
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_USER=vulcanize
      - DATABASE_PASSWORD=vulcanize
      - STARTING_BLOCK_NUMBER=8928152
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--strict", "--", "./startup_script.sh"]
    restart: unless-stopped

  execute:
    image: makerdao/vdb-execute:v1.0.1-mainnet-lite-with-recheck
    env_file: mainnet-1.0.1.env
    environment:
      - CLIENT_IPCPATH="https://geth0.mainnet.makerfoundation.com:8545"
      - DATABASE_NAME=vdb
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_USER=vulcanize
      - DATABASE_PASSWORD=vulcanize
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--strict", "--", "./startup_script.sh"]
    restart: unless-stopped

  db:
    image: postgres:12.1-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_DB=vdb
      - POSTGRES_USER=vulcanize
      - POSTGRES_PASSWORD=vulcanize
    restart: always

  postgraphile:
    image: makerdao/vdb-postgraphile
    environment:
      - SCHEMAS=api
      - DATABASE_URL="postgres://vulcanize:vulcanize@db:5432/vdb"
    depends_on:
      - db
    restart: always
